

#define VOLMJHK_TYPE 40000


#define	IOCTL_VOLMJHK_HOOK       CTL_CODE(VOLMJHK_TYPE, 6, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define	IOCTL_VOLMJHK_UNHOOK     CTL_CODE(VOLMJHK_TYPE, 7, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define	IOCTL_VOLMJHK_HOOKLIST   CTL_CODE(VOLMJHK_TYPE, 8, METHOD_BUFFERED, FILE_ANY_ACCESS)